# Generated by Django 4.0.5 on 2022-07-06 18:40

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_location_unique_location_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='location',
            name='unique_location_name',
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_location_name'),
        ),
    ]
