# Generated by Django 4.0.5 on 2022-07-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_location_unique_location_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='location',
            name='unique_location_name',
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
